version: "3.9"

networks:
  mcp_net:
    driver: bridge

services:
  mcp-server:
    image: ghcr.io/sooperset/mcp-atlassian:latest
    container_name: mcp-server
    ports:
      - "9000:9000"
    env_file:
      - .env   # contains CONFLUENCE_*, JIRA_*
    command: --transport sse --port 9000
    restart: always
    networks:
      - mcp_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/sse"]
      interval: 30s
      timeout: 5s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: mcp-proxy
    depends_on:
      - mcp-server
    ports:
      - "9001:9001"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    restart: always
    networks:
      - mcp_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    depends_on:
      - nginx
    ports:
      - "3000:8080"
    volumes:
      - ./openwebui-config.json:/root/.open-webui/config.json
    environment:
      - OPENAI_API_BASE_URL=http://host.docker.internal:1234/v1
    restart: always
    networks:
      - mcp_net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 30s
      timeout: 5s
      retries: 3
